language: csharp
solution: WHIP_LRU.sln

mono:
- 4.6.1

cache:
  directories:
  - packages

before_script:
- if [ "$TRAVIS_TAG" ]; then export TAG_VERSION="$TRAVIS_TAG.$TRAVIS_BUILD_NUMBER"; else export TAG_VERSION="v1.0.0.$TRAVIS_BUILD_NUMBER"; fi
- export TAG_VERSION=`echo $TAG_VERSION | sed 's/v//'`
- echo "Setting version to '$TAG_VERSION'"
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/LibWhipLru/Properties/AssemblyInfo.cs
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/WHIP_LRU/Properties/AssemblyInfo.cs
- sed -i 's/COMPILED_BY = "?mono?"/COMPILED_BY = "Mono"/' Source/WHIP_LRU/Program.cs
- sed -i 's/COMPILED_BY = "?mono?"/COMPILED_BY = "Mono"/' Source/RollbarCrashReporter/CrashReporter.cs

before_deploy:
- >-
  if [ "$TRAVIS_TAG" ]; then
    export ENVIRONMENT=production
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="production"/' bin/WHIP_LRU.exe.config;
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="production"/' bin/RollbarCrashReporter.exe.config;
  else
    export ENVIRONMENT=test
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="test"/' bin/WHIP_LRU.exe.config;
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="test"/' bin/RollbarCrashReporter.exe.config;
  fi
- mv bin WHIP-LRU
- zip -r WHIP-LRU-mono.zip WHIP-LRU > /dev/null

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "KwxP3gWGI0Aw+lbAPO6jTSfvv4M+744W3JgLbiYGvITmd9ONGza45LNW2bUasu16D50dE5DmB0v22wvRWHlfChzYYLarzis/BYIjU6RDRMnQW2FKkQqdjg1GJVC5EXpnGhXUwuBekfLM2XnCLr4FcgTDUM3logWiqz0z3w5a4AC3Q9FC3w+tqsSe3kieKuWs54qeP9g8o1mi6oOFPA58E/1tBPBLXfhfE3NznQ4Z65zWVKPV8hmGO+787uF2QPc7TjuVbRCpwb/YwFfusbIg8Jv1em4ej2VJL/soLDWNMrUj/r+DCfALblgtclxTxax08iitSYaM0TjBK85CtDmHinaOIde72nL3IefTPJEupbB784Kplro1MgJTM9d0sWNUmicn5KxWWIK5thOax6qxhciG8NNO1nPTnV91/7KUeOIefNKYDivxfdfgYLuDBQmUgvy6H6ajrlUQU5JJ5BSxBKMdOjLQpsyTyCHLN6HYKErPinJWTldNmULwkQ54A2qVakzusb3en6gZMWHRurfWflwlVv02LQNuGKg8Ma7DDfLVxiiAhPrUmNn1EZ9/zuoelnRjlmyOMxzF12ppx5/t7+CT9F09leXom8CKCJDI5UK3W/N3N6Mms+52wO5LyDndv6kTooUZYhpzUzjAIh5/tqsnVzJfFDMmZ9VxcQgDsPA="
  file: WHIP-LRU-mono.zip
  draft: true
  on:
    repo: kf6kjg/WHIP-LRU
    tags: true

after_deploy:
- export LOCAL_USERNAME="`git log -n 1 --pretty=format:"%an"`"
- export REVISION="`git log -n 1 --pretty=format:"%H"`"
- curl https://api.rollbar.com/api/1/deploy/ -F access_token="$ACCESS_TOKEN" -F environment="$ENVIRONMENT" -F revision="$REVISION" -F local_username="$LOCAL_USERNAME"

